# Generated by Django 3.0.8 on 2020-07-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_student_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=250)),
                ('contact_number', models.IntegerField()),
            ],
        ),
    ]
